### ISSUE TITLE
form input is not sanitized

### ISSUE THREAD

**Issue by amsibamsi** [puzzle/cryptopus#12]
tested on ruby1.8/rails2 version. vulnerable to xss.

you can enter html/js code e.g. as description of an entry. this will then be evaluated in the browser on a client when visiting the entry. it is not properly escaped as text when the page is rendered. what harm can be done with this ... ? e.g. make another user deleting entries when visiting your entry by injecting code that guesses the right url to edit/remove entries.

**Comment by puzzleitc** [comment]
code injection is now prevented in all user editable fields.
