### ISSUE TITLE
Handle users that got removed from LDAP

### ISSUE THREAD

**Issue by ZeroPointEnergy** [puzzle/cryptopus#13]
At the moment if a user is no longer in LDAP the name "No No" is displayed. This should be handled differently so that cryptopus remembers what the username was and display that it is no longer possible to login with this user.

**Comment by mzurbuchen** [comment]
https://github.com/mzurbuchen/cryptopus/commit/044fdc4556fd17dd7b66db19992ec71b161e2db3
