### ISSUE TITLE
Disable autofill in username/password fields

### ISSUE THREAD

**Issue by codez** [puzzle/cryptopus#133]
For accounts, username and password form fields are automatically filled by the browser (using the login credentials for cryptopus itself). This is not only annoying, but also data issue: If I create an account without a username, only with a password, and edit it again (for example to change the description), the username 
AND password are auto-filled, too. Hence I lose my saved password, as it got replaced by the auto-filled one.

Usually, autocomplete="new-password" should fix this issue.

**Comment by psunix** [comment]
@mzurbuchen could you fix that one too ?

**Comment by psunix** [comment]
autocomplete="new-password" only works with webkit based browsers. 
found a better solution which should support all major browsers. 
https://stackoverflow.com/questions/36935576/how-to-make-input-type-tel-work-as-type-password/36950075#36950075
