### ISSUE TITLE
Add show password link in password field

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/cryptopus#155]
After I opened an account item (that contains a password) and the edit it, the password field is empty.
<img width="840" alt="grafik" src="https://user-images.githubusercontent.com/7139459/51822051-6047a100-22db-11e9-8041-3062f112894c.png">

This indicates to the user, that there is no password stored - even though there is. 

Furthermore it is unclear, what happens after I changed other fields than the password field: is the password reset to "no password" or do I have to enter something in this field?

Please add the "Show password" link in the edit mode of an account, so that the user has the feedback, that there is a password for that account item.
<img width="294" alt="grafik" src="https://user-images.githubusercontent.com/7139459/51822144-a7ce2d00-22db-11e9-8fbe-155ad1ddfc61.png">

**Comment by psunix** [comment]
this should be obsolete with #161 since we're showing ****** again for existing passwords
