### ISSUE TITLE
geoip gem is not working currently

### ISSUE THREAD

**Issue by psunix** [puzzle/cryptopus#162]
the GeoIP database format has changed and is now incompatible with geoip's current implementation. discussed in this issue: https://github.com/cjheath/geoip/issues/75
there seems to be an official ruby lib now from the db creator itself. https://github.com/maxmind/MaxMind-DB-Reader-ruby

this issue currently blocks travis and creating a new release of Cryptopus. I'll probably have some time to look into it in the next 3 weeks. If someone else want to do some research, this would be very welcome :)

**Comment by PhilipSchmid** [comment]
Hi @psunix,
Does this issues have something to do with the following error?

```
Found post_assemble script at .s2i/post_assemble, executing it
~ ~
+ pushd /opt/app-root/src
+ bundle exec rake geo:fetch
rake aborted!
Zlib::GzipFile::Error: not in gzip format
/opt/app-root/src/lib/tasks/geo.rake:19:in `initialize'
/opt/app-root/src/lib/tasks/geo.rake:19:in `new'
/opt/app-root/src/lib/tasks/geo.rake:19:in `block (2 levels) in <top (required)>'
/opt/app-root/src/bundle/ruby/gems/airbrake-6.1.2/lib/airbrake/rake.rb:19:in `execute'
/opt/app-root/src/bundle/ruby/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => geo:fetch
(See full trace by running task with --trace)
```

Thanks & regards,
Philip
