### ISSUE TITLE
Improve Docker Hub Build and Docker image

### ISSUE THREAD

**Issue by PhilipSchmid** [puzzle/cryptopus#164]
Hi there,

I saw that the Docker image on the Docker Hub is not up to date (2 months old) and is only available with the `dev` tag. That's the reason why I created an own build but unfortunately this build currently fails (probably because of https://github.com/puzzle/cryptopus/issues/162).

I think it would be nice to see an improved automated Docker Hub build. Would that also be in your interest? For automated version based Docker image builds on the Docker Hub, please feel free to take the scripts from https://github.com/HSRNetwork/docker-cryptopus/tree/master/hooks.

I also saw that you use `puzzle/ose3-rails` as base image in your Dockerfile. This basically means you are using the `latest` tagged `puzzle/ose3-rails` image which is 2 years old... Wouldn't it make sense to use a newer base image like used inside https://github.com/HSRNetwork/docker-cryptopus/blob/bd63c7fc9e8c5efd36ab893f5dc6019bb1bc8f46/Dockerfile#L1?

Thanks!

Regards,
Philip

**Comment by psunix** [comment]
Hi

the docker image is WIP for now. As soon as @janissbinder has tested the changes which should fix #162 I will create a stable docker image version. You were correct in assuming this causes the build error.

nice to see that others are interested in having a docker image too :)

Cheers

psunix aka psymon

**Comment by psunix** [comment]
just updated the docker hub build settings. *latest* points now to *master* and is built from ose3-rails:ruby22. also see https://github.com/puzzle/cryptopus/wiki/Docker
*stable* build will be available as soon as @janissbinder tested the geo_ip fix and merged it into master.
@janissbinder for puzzle integration env: should be possible to use the image built on docker hub now. this should make it pretty easy to set it up. (the cryptopus int env was broken last time I checked)

**Comment by PhilipSchmid** [comment]
@psunix Awesome, thanks! So then let's wait for #162 to be resolved in order to further improve the Docker Hub build.

Regards,
Philip

**Comment by psunix** [comment]
a stable docker image is now available :) check wiki/Docker for instructions
