### ISSUE TITLE
Change Delete Icon

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/cryptopus#165]
Please change this delete Icon:
![grafik](https://user-images.githubusercontent.com/7139459/53638179-c77faa80-3c25-11e9-9b5f-9569ac2059b2.png)

to a trash can delete icon, for example like this:
![grafik](https://user-images.githubusercontent.com/7139459/53638281-0ca3dc80-3c26-11e9-84cb-6b9be645fd37.png)

Why? 
Because the delete action uses in most cases a trash can icon and people are used to it.

I will create a different issue with some propositions for some open source icon libraries.

**Comment by Thunderguts13** [comment]
The delete icons are now trashcans
