### ISSUE TITLE
Improve UX in expanded search result view

### ISSUE THREAD

**Issue by Joshuasony** [puzzle/cryptopus#168]
When I expand an account in the search result view, the arrangement of the entry changes. It confuses me, that the "team-group" information changes its location from right to the left side. Why?

If we implement this issue https://github.com/puzzle/cryptopus/issues/167, there is almost no use for this view. Adding the description of the account would make it useful again. Because if the description is the discerning information that I need in order to find the account i'm looking for, it's bad for the user experience to having to go to the acount page. Also I am not able to browser back to the search result view (in the case that it was not the account I was looking for), which destroys the user experience entirely. 

This is why I am suggesting to add the description in the expanded search result view and display it like so:

![grafik](https://user-images.githubusercontent.com/7139459/53639905-dfa5f880-3c2a-11e9-98f0-c6c81f70c380.png)

**Comment by m4rc77** [comment]
Adding the description ("Beschreibung") from each entry to the https://server/teams/nnn/folders/nnn view would be a great improvement!
