### ISSUE TITLE
geoip .dat file updates

### ISSUE THREAD

**Issue by lukpre** [puzzle/cryptopus#172]
Hey

Is it possible that the GeoIP data files cryptopus uses are out of date ? 
Having the issue that an IP Range from QuickLine AG is not recoginzed as Swiss IP Range.

https://db-ip.com/all/139.178.2

Best regards

**Comment by psunix** [comment]
Hi

the geo ip db is updated with `rake geo:fetch`. have you tried to update it?
for us the ip/country mapping was pretty reliable so far. 
when we build the official docker image, the db is fetched once and integrated. https://cloud.docker.com/repository/docker/puzzle/cryptopus/tags

Cheers

psunix
