### ISSUE TITLE
User cannot be deleted

### ISSUE THREAD

**Issue by psunix** [puzzle/cryptopus#174]
when a Admin or ConfAdmin tries to delete a User, it just doesn't work without any hint about the problem. 

ajax request for deleting an user results in 403. 

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

add some more tests: https://github.com/puzzle/cryptopus/blob/master/test/controllers/api/admin/users_controller_test.rb, https://github.com/puzzle/cryptopus/blob/master/test/features/user_feature_test.rb

**Comment by Thunderguts13** [comment]
Issue can't be reproduced
