### ISSUE TITLE
Missing HTML class "secret" on setting_ldap_bind_password input

### ISSUE THREAD

**Issue by rekup** [puzzle/cryptopus#175]
The input field for the ldap binduser password does not have the HTML class `secret`. As a result the password is readable:

`<input type="text" name="setting[ldap_bind_password]" id="setting_ldap_bind_password" value="" class="form-control" data-kpxc-id="setting_ldap_bind_password">`

Should be
`
<input type="text" name="setting[ldap_bind_password]" id="setting_ldap_bind_password" value="" class="form-control secret" data-kpxc-id="setting_ldap_bind_password">`

**Comment by psunix** [comment]
we're going to move the ldap settings to either conf file or env vars. so this password inputs are going to be removed soon :)
