### ISSUE TITLE
Wrong link in breadcrumbs

### ISSUE THREAD

**Issue by carlobeltrame** [puzzle/cryptopus#215]
When I am viewing the details of an account (https://cryptopus.puzzle.ch/accounts/<accountId>) and click the team name in the breadcrumbs (Teams / **{teamName}** / {groupName} / {accountName}), the link takes me to https://cryptopus.puzzle.ch/teams/{teamId}/groups/{accountId}. Since the account id is not a group id, this leads to a "Not Found" error most of the time.
When viewing other sites (e.g. the group view https://cryptopus.puzzle.ch/teams/{teamId}/groups/{groupId}), the breadcrumb link works as expected (https://cryptopus.puzzle.ch/teams/{teamId}).

**Comment by LBruegger** [comment]
This Bug is fixed now and will be released in the next version of Cryptopus. Thanks for your Issue.
