### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by nerrehmit** [puzzle/cryptopus#256]
Hi

I noticed several missing translations at least in the language "ch_be" eg. "Bärndütsch" but I suspect they are missing in other languages as well, that's why I did not create a PR.

Let me know if you need help with the "Bärndütsch" expressions.

Following is missing:
ch_be.admin.teams.index.teamname
ch_be.admin.teams.index.folders
ch_be.admin.teams.index.accounts
ch_be.admin.teams.index.members

ch_be.maintenanance_tasks

ch_be.executed_at
ch_be.status
ch_be.output
ch_be.executer

Note that "executer" probably is a typo and should be called "executor" in english.

If I am on my own account page and want to add a new api user the Button says "New" even though I have a different language selected.

Maybe there is a way to check if all the translations for a specific language are present?

**Comment by lucashabersaat** [comment]
Thanks for your feedback. This has been forgotten. We will add atleast the swiss translation in the next release.

**Comment by lucashabersaat** [comment]
This issue has been fixed in #258
