### ISSUE TITLE
link to wiki does not work

### ISSUE THREAD

**Issue by mgafner** [puzzle/cryptopus#34]
Auf https://github.com/puzzle/cryptopus ist zuoberst ein Link auf ein Wiki der ins Leere zeigt (http://sourceforge.net/projects/cryptopus.wiki/)

**Comment by mgafner** [comment]
mittlerweile habe ich mal die links auf sourceforge.net updated (https://sourceforge.net/projects/cryptopus/).

kann mir jemand write rechte auf cryptopus geben, damit ich die description updaten kann?

**Comment by phil-pona** [comment]
Habe den Link angepasst, allerdings stellt sich mir die Frage, ob neu der Master eher das Github Projekt ist, und nicht das Sourceforge Projekt. Evt. sollten wir den Link ganz entfernen auf Github

**Comment by psunix** [comment]
yes, wir werden das beim bevorstehenden Release 2.0 berücksichtigen.

**Comment by mgafner** [comment]
Ja eigentlich sehe ich auch Github als Master ;-)
