### ISSUE TITLE
Accessing a group or credential without permissions leads to "Missing translation "en.[object Object]" for locale "en"

### ISSUE THREAD

**Issue by buehlmann** [puzzle/cryptopus#352]
I get an error  _"Missing translation "en.[object Object]" for locale "en"_ when trying to open a group or credential for which I have no access rights. This is a quite confusing message.

Probably related to https://github.com/puzzle/cryptopus/issues/325.

**Comment by nerrehmit** [comment]
I'm having the same issue. I think the missing translation is misleading as I get that notification regardless of language chosen.
