### ISSUE TITLE
Error: sqlite version too old

### ISSUE THREAD

**Issue by daniel-illi** [puzzle/cryptopus#353]
With the current docker container from docker hub I get the following error:
```
RuntimeError (Your version of SQLite (3.7.17) is too old. Active Record supports SQLite \u003e= 3.8.):\n","stream":"stdout","time":"2021-02-04T09:31:20.973871602Z"}
```

This causes the application startup to fail.

This is the exact image:
https://hub.docker.com/layers/puzzle/cryptopus/latest/images/sha256-70fdbcd46a6757d031f1f6c88d34438a1702396f0d4f3ca2b4f6fa3194129ae4?context=explore

**Comment by psunix** [comment]
yes ... sqlite is currently not supported with this docker image.  #196 there's already an issue. 

is it possible for you to use mysql? https://github.com/puzzle/cryptopus/wiki/Docker

**Comment by daniel-illi** [comment]
merci :+1:
