### ISSUE TITLE
Click to Copy for Passwords is not working

### ISSUE THREAD

**Issue by Aedu** [puzzle/cryptopus#37]
Copy to Clipboard is not working. 
Also the "Show password" has a Problem. It will be not displayed... (is just flashing up (short))
Tested with IE and FF.

IE Debugger shows the following: 
 AccountHelper.showCopyMessage = function(e, name) {
      var div, message, parent;
      parent = $(e.target.closest(name)).parent();
Das Objekt unterstützt die Eigenschaft oder Methode "closest" nicht
      if ($(parent).hasClass('result-password select-click')) {
        message = '<p class="copied" >Password copied! </p>';
        div = '.result-password';

**Comment by janissbinder** [comment]
I fixed this error. Please reopen this issue if the error still appears on your system.
