### ISSUE TITLE
Ember Update

### ISSUE THREAD

**Issue by TheWalkingLeek** [puzzle/cryptopus#372]
Current version: 3.19
Target LTS version: 3.24

There exists an addon, helping to upgrade an ember app (https://cli.emberjs.com/release/basic-use/upgrading/#howtodoanupgrade). Maybe try updating it with smaller steps and always checking for errors. This Addon can really help, but also break a lot of stuff. Make sure to remove it again, once you're done upgrading :)

**Comment by LivioLiechti** [comment]
https://emberigniter.com/update-latest-ember-data-cli/

**Comment by luca-bruegger** [comment]
Umsetzung:
- [ ] Lesen was alles geändert wurde
- [ ] Update ausführen
- [ ] Code aktualisieren
- [ ] Tests beheben
- [ ] Manual Testing
