### ISSUE TITLE
Tubolinks.enableProgressBar not supported and HTML1114

### ISSUE THREAD

**Issue by Aedu** [puzzle/cryptopus#38]
Can you please double check when using the 2.0.0 Version with IE or FF in Debug Mode if you get the same Errors?  Would be great to have a fix for this. Thanks

Tested also with IE and FF.
IE Debugger Shows the ProgressBar Error:
Datei: application-8576a738212cacc3857b53f05d7f5d8be246282b46822ed9bf87cdc2a0ebb250.js, Zeile: 33725, Spalte: 3

-> 33725
Turbolinks.enableProgressBar();
Das Objekt unterstützt die Eigenschaft oder Methode "enableProgressBar" nicht

Then in the same file for Login (at Login page) we get a warning HTML1114:
Die Codepage "utf-8" von (HTTP-Header) überschreibt die Konflikte verursachende Codepage "us-ascii" von (META-Tag).

**Comment by psunix** [comment]
probably fixed with most recent browser versions. 
feel free to open a new issue if the problem still exists.
