### ISSUE TITLE
Click to Copy for Passwords is still not working

### ISSUE THREAD

**Issue by Aedu** [puzzle/cryptopus#39]
The Problem still persists

Copy to Clipboard is not working.  Try copy to clipboard and insert into Notepad... it does not copy it into clipboard... don't know where it goes. 
 Also the "Show password" has a Problem. It will be not displayed... (is just flashing up (short))
When you did "Show Password" then you push in the IE one page back (with the IE Flash <- )
You see the Password field alone with the Password shown in it. 

Under TEAM-GROUP-ACCOUNT the behavior is like descripted above. 

Under the Search "Want to recover a password?" the "Show Password" is working correct,
but the "copy to clipboard" doesn't. 

Tested with IE and FF.

The other Debug IE Problem is fiixed, like you mentioned. (no more Message shown)

**Comment by psunix** [comment]
please provide us with more information. is there any js error ? 
what versions of FF and IE are you using ?
on linux and mac this works fine for us.

**Comment by DominikFischli** [comment]
Closing as outdated
