### ISSUE TITLE
ADMIN: Move Settings to emberjs/api

### ISSUE THREAD

**Issue by TheWalkingLeek** [puzzle/cryptopus#391]
currently, admin -> settings is server side rendered in classic rails app part. the goal of this issue is to move it to api and emberjs. 

![image.png](https://images.zenhubusercontent.com/60182665657f47903bf9cfb6/8dc0e48e-4e69-4511-b4b5-11b3829d544a)

# Tech-Spec

## Backend
- [x] Create new controller api/admin/settings_controller.rb, use dry crud, only use index and update actions
- [ ] Create db migration to migrate Settings keys and remove prefix: general_country_source_whitelist -> country_source_whitelist
- [x] Create routes entries, only: index, update
- [x] Create new serializer for setting: app/serializers/setting_serializer.rb (output attrs key, value)
- [x] remove existing SSR settings controller and spec
- [ ] create seeder for both setting entries, make sure seeding is done in development and production env (adjust entrypoint ?)

## Frontend
- [x] Create new Drop-Down Admin in Topbar and add Settings item
- [x] New Route app/routes/admin/settings.js
- [x] New Template app/templates/admin/settings.hbs (inlcudes multiselect for ip_whitelist, country_source_whitelist)
- [ ] New Component app/components/admin/setting_multiselect.js
- [x] Power-select-multiple https://ember-power-select.com/docs/multiple-selection/
- [x] Addon for countries -> Send iso codes to backend
- [ ] No save button, just update settings when hitting enter or leaving input field
  - [ ] In return, each Input in the form needs an `@enter` and `@focus-out` action which save the newly edited data (check if there were changes!)

**Comment by luca-bruegger** [comment]
Umsetzung:

- [ ] Ember Components erstellen.
- [ ] Rails routing anpassen.
- [ ] Countries Addon evaluieren & installieren
- [ ] Rails Controller Anpassen
- [ ] Rails Tests entfernen & Ember tests schreiben.
- [ ] Manual Testing.

**Comment by LianVin** [comment]
Länderdropdown wurde erstellt und befüllt. Es wird Momentan noch nichts ans Backend geschickt. 
Ich habe bereits versucht mittels ENTER eine Methode im app/components/admin/setting_multiselect.js aufzurufen. Funktioniert aber noch nicht.

**Comment by LianVin** [comment]
Validierungstest im Backend für IP und Country wurden erstellt.
