### ISSUE TITLE
Puzzle Shell Init

### ISSUE THREAD

**Issue by TheWalkingLeek** [puzzle/cryptopus#404]
Implement the new Header & Footer Style

<img width="1976" alt="footer header_old" src="https://user-images.githubusercontent.com/52595924/118493515-7e8e7080-b721-11eb-8659-709513bc70f4.png">

**to This**

<img width="785" alt="footer header" src="https://user-images.githubusercontent.com/52595924/118492378-3e7abe00-b720-11eb-8417-77eb2bd0cb1f.png">

# Tech Spec
- [x] Finish Topbar in Storybook
- [x] Finish Footer in Storybook
- [x] Create npm package or use [npm link](https://docs.npmjs.com/cli/v6/commands/npm-link)
- [x] Remove Cryptopus Topbar & Footer
- [x] Implement PuzzleShell Components
- [x] Manual & Automated testing

## Shorthand form:
- Create Topbar and Footer Component.
- Add them to Cryptopus with npm-package.

**Comment by psunix** [comment]
@luca-bruegger please specify
