### ISSUE TITLE
ADMIN Users list actions

### ISSUE THREAD

**Issue by TheWalkingLeek** [puzzle/cryptopus#415]
## Backend
- [x] Serialize auth provider on users#index, show edit button if not oidc
- [x] Rename Api Route (PATCH /api/admin/users/:id/update_role -> PATCH /api/admin/users/:id/role) https://github.com/puzzle/cryptopus/blob/master/config/routes/api.rb#L35
## Frontend
- [x] Create admin/user-form component modal (https://www.ember-bootstrap.com/components/modal/) 
  - example:
     - js: https://github.com/puzzle/cryptopus/blob/master/frontend/app/components/account-form.js 
     - hbs: https://github.com/puzzle/cryptopus/blob/master/frontend/app/templates/components/account-form.hbs
- [ ] Create user-human validator
- [x] Send api call (api url: /api/admin/users/:id/role) for updating role onChange on dropdown https://ember-power-select.com/docs/action-handling/ 
- [x] create deletion component
- [x] might have to adjust user-human adapter for deletion -> consult with @TheWalkingLeek

**Comment by psunix** [comment]
it just came up my mind that there's different rules for setting the user role. 
for example, if you're a Conf Admin, you cannot upgrade any user to Admin.
also you cannot down-grade an Admin to Conf Admin.
@TheWalkingLeek did you take this into account?
