### ISSUE TITLE
Accounts with empty Username can not be edited

### ISSUE THREAD

**Issue by m4rc77** [puzzle/cryptopus#448]
**Problem**:
I created a new account to store a SSH-key. In order to do so, i only filled the fields `Accountname` and `Description` then i uploaded on /accounts/yyy the SSH-key file. Later I tried to update the `Description` and tried to edit the account from /teams/nnn/folders/mmm page **but the `Edit Account` button did not do anything!**

**Analysis**:
Accounts with a empty 'Username' field can not be edited by clicking on the `Edit Account` button on /teams/nnn/folders/mmm on  or /accounts/yyy page.

Thanks for fixing this issue.

PS: you can find such a account on https://[integration-server]/teams/211/folders/693 ;-)

**Comment by TheWalkingLeek** [comment]
Fixed this in #449 
Gonna be live in the next release, thanks for reporting! :)
