### ISSUE TITLE
Admin pages can't be opened after search

### ISSUE THREAD

**Issue by ombre8** [puzzle/cryptopus#465]
When I search for something and then want to open an Admin Page, the search results are reloaded "over" the admin page again. I have to delete the search term manually to navigate to an Admin Page.

Expected Behavior: If I klick on a link in a navigation, that page is actually displayed and not overloaded with something I might have looked at before.

**Comment by TheWalkingLeek** [comment]
Thanks for reporting!
Fixed this in https://github.com/puzzle/cryptopus/commit/c77ec34ba5e870e0b65817805b64616a153a4d7c
and will be live in the next release :)
