### ISSUE TITLE
server-side session expiration 

### ISSUE THREAD

**Issue by pgassmann** [puzzle/cryptopus#48]
The logout after 5 minutes is implemented in Javascript only.
When you close the site without logging out, the session remains open. This morning when I started my computer and opened the browser, I was still logged in to cryptopus, because I was logged in when I shut down the computer.

Session expiration should be implemented server-side.

**Comment by psunix** [comment]
server side session expiration is configured already. https://github.com/puzzle/cryptopus/blob/master/config/initializers/session_store.rb

just tested it on a productive system and it seems to work.

login in cryptopus and disable javascript. wait for about 6 minutes (the timeout is set to 5 mins) and click any link in the current cryptopus window. you should be redirected to the login window.
