### ISSUE TITLE
ENCRYPTABLES: Fix system spec after accounts to encryptables rename

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#517]
at branch feature-encryptables are the system specs currently not running after merge of #514 

- [x] Fix system specs and double check frontend files for pending renaming from account to encryptable
- [x] Update Translations

**Comment by lkleisa** [comment]
I started with renaming from account to encryptable, finished with mostly every variable. Start also removing unused translations but didn't finished yet

**Comment by lkleisa** [comment]
Useful tool for checking if translation is unused: https://github.com/glebm/i18n-tasks
But it it does not work well.

**Comment by lkleisa** [comment]
I removed all unused translations for the backend in every language. I removed also some translations in frontend, but not much. 5 System specs are failing, I will fix it when I'm back

**Comment by lkleisa** [comment]
There was a bug with the search, that it rendered too early and too much. I tried to fix that, but now there are some errors. The search can't be quitted with the icon and when there was a search, all folders are automatically expanded.

**Comment by lkleisa** [comment]
Created a pull request for the translations: https://github.com/puzzle/cryptopus/pull/602
