### ISSUE TITLE
Feature: Provide sorting in admin/users view

### ISSUE THREAD

**Issue by nerrehmit** [puzzle/cryptopus#541]
This is a feature request coming from a conf-admin in a cryptopus instance.

I'd like to be able to sort different columns in the admin/users view. Currently the list of users seems to be sorted based on the user-names with no possibility to change this from a user perspective.

For security or off-boarding purposes it would be convenient if one could sort the column "Last login at" either ascending or descending.

Can be done in ember only. Default order is username.

# DoD

- The admin/users table can be sorted by any of the attributes in the table
- Additional tests have been written for said functionality
- All tests still pass

**Comment by Robin481** [comment]
Definition of Done:
- The admin/users table can be sorted by any of the attributes in the table
- Additional tests have been written for said functionality
- All tests still pass
