### ISSUE TITLE
LOG: Personal activity log with previous values

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#571]
The idea of this feature is to log all personal changed or accesses to encryptables with old and new values.  

![Mockup deluxe version](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/images/PersonalActivityLogDeluxe.png?raw=true)

This feature is based on: [Access- and changelog conception](https://github.com/puzzle-bbt/kon-cryptopus-access-log-history/blob/main/README.md) and previous [Issue 564](https://github.com/puzzle/cryptopus/issues/564) and [Issue 568](https://github.com/puzzle/cryptopus/issues/568) 

Always run the E2E-tests if you change something in the frontend, run the backend-tests if you change something in the backend and test always manually

# ToDo
- [ ] Add previous values of an attribute to the table, same as we have done it in [Issue 565](https://github.com/puzzle/cryptopus/issues/565)

**Comment by mtnstar** [comment]
if think this is not required.
if the user wants to access previous value, he can just go to encryptable version page
