### ISSUE TITLE
rename User's uid attribute to ldap_uid

### ISSUE THREAD

**Issue by psunix** [puzzle/cryptopus#59]
uid seams to be used only for ldap uid (check first)

if this is confirmed, rename the attribute to ldap_uid

- create new migration to rename attribute on table users
- make sure to replace uid with ldap_uid where used

**Comment by mzurbuchen** [comment]
https://github.com/mzurbuchen/cryptopus/commit/718bfbcce8e8c0a5033910f381864607dac006b6
