### ISSUE TITLE
CCLI: Copy login command does not work, ccli login fails

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#627]
I had to revert commit 4d839a96acc505e3cadab66aa284a885905ead5e

CCLI - cryptopus command line client

- it creates a new api user every time I click **Copy CCLI Login**
  - it should only create a new api user with ccli default if none is present
- login does not work with ccli 1.1.0, authentication failed
  - login should be possible with current version 1.1.0 of ccli

https://github.com/puzzle/ccli/

**Comment by kcinay055679** [comment]
Due to very limited usage of the CCLI, we have decided not to maintain it any further.
