### ISSUE TITLE
Frontend Upgrade

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#665]
Some months ago, we upgraded our frontend gems and dependencies in [this issue](https://github.com/puzzle/cryptopus/issues/536).
This must now be done again

### ToDo
- [ ] Get familiar with the [frontend upgrade guide](https://github.com/puzzle/cryptopus/wiki/Frontend)
- [ ] Upgrade available dependencies and gems
  - Packages that cause Dependabot alerts
    - [ ] async
    - [ ] actionpack
    - [ ] actionview
    - [ ] minimist
    - [ ] moment
    - [ ] ansi-regex

**Comment by mtnstar** [comment]
# Frontend Upgrade Guide

## Useful tool to check outdated dependencies
https://www.npmjs.com/package/npm-check

## Workflow
When npm-check asks if dependency is still used

1. Remove it in package.json
2. Execute yarn install in the emberconsole inside the docker-image.
3. Restart the docker-image
4. Run tests in localhost:4200/tests
5. If tests fail add dependency back to package.json

When npm-check tells you that a dependency is outdated

1. Change the version to the version you want to upgrade it to
2. Execute yarn install in the emberconsole inside the docker-image.
3. Restart the docker-image
4. Run tests in localhost:4200/tests
5. If tests fail downgrade version to newest working version

After upgrading all dependencys in package.json check Dependabot for leftover security allerts

If security alerts are coming from a dependency not used in package.json check why it is used with `yarn why <dependency_name>`
