### ISSUE TITLE
Falsches Icon bei privaten Teams

### ISSUE THREAD

**Issue by bsantschi** [puzzle/cryptopus#669]
Im Baum im linken Bereich habe ich mehrere Teams, zum Teil private wie auch nicht-private. Wenn ich mich in Cryptopus anmelde, erscheinen bei allen Einträgen das Icon members.svg, bei den privaten Teams sollte jedoch das Icon encrypted_small_white.svg erscheinen. 

![1](https://user-images.githubusercontent.com/108862416/195508203-07a9b241-bcc7-4ff0-8e51-78c00d63bc7f.png)

Sobald ich auf ein privates Team klicke, wird das Icon dann korrekt angezeigt:
![2](https://user-images.githubusercontent.com/108862416/195508100-f1956acb-75e6-4368-a5e2-77b41b61a5f1.png)

Das Fehlverhalten ist nicht schlimm, aber es gibt einem aus Sicht Security ein ungutes Gefühl, denn es lässt vermuten, dass andere auf die privaten Einträge Zugriff haben.

**Comment by MarcEgliP** [comment]
Vorgehen:

- [] Komponent ausfindig machen
- [] Altes Icon eliminieren und neues Icon einfügen
