### ISSUE TITLE
ENCRYPTABLES: remove ose secrets

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#683]
since we do not use ose secrets in cryptopus anymore, we're going to remove it. 

# Todo

- Remove `app/models/encrytable/ose_secret.rb`
- Remove all related backend specs
- Remove ose secret related frontend code
- Remove all related frontend tests
- anything else related to ose secrets to remove? doc? 
- create ticket to clean-up ccli (command line client) https://github.com/puzzle/ccli
- Remove all existing OseSecrets at Cryptopus Prod (@mtnstar)

**Comment by lkleisa** [comment]
Ticket for clli -> https://github.com/puzzle/cryptopus/issues/706
