### ISSUE TITLE
Upgrade Boostrap to most recent version

### ISSUE THREAD

**Issue by mtnstar** [puzzle/cryptopus#698]
we're currently using bootstrap 3 for styling the UI. Goal of this ticket is to upgrade to the most recent version 5.3.

# Tech-Spec

- https://getbootstrap.com/
- https://github.com/puzzle/cryptopus/blob/master/frontend/package.json#L33

**Comment by MarcEgliP** [comment]
Stand heute:
- Bootstrap wurde auf die Version 5.3.0-alpha3 geupgradet
- Jegliche Überarbeiteten Klassen des Upgrades wurden angepasst

Was noch gemacht werden muss:

- [ ] ember-bootstrap verwendet noch nicht Bootstrap 5 dies sieht man an folgendem screenshot:

![Image](https://github.com/puzzle/cryptopus/assets/88040929/518c1115-a7eb-4ece-8f06-cec892f84546)

Hierbei handelt es sich um einen ember-bootstrap Komponenten von: https://www.ember-bootstrap.com/api/classes/Components.Modal.html
, jedoch greift dieser noch nicht auf Bootstrap 5 zu. Um das zu ändern habe ich bis jetzt folgende Angaben gefunden:

- https://www.ember-bootstrap.com/getting-started/setup (Switch von Bootstrap 4 zu Bootstrap 5)
- Evtl. muss die Version von Ember-Bootstrap selbst verändert werden, dann kann dies hilfreich sein: https://www.ember-bootstrap.com/changelog
- Allenfalls kann hier noch Hilfe gesucht werden: https://stackoverflow.com/questions/51723010/ember-project-crashes-after-upgrading-bootstrap-from-4-1-2-to-4-1-3

**Comment by kcinay055679** [comment]
To update ember bootstrap you need at least ember 4.0 which is part of the following ticket #709

**Comment by MarcEgliP** [comment]
## Strategie 18.07.2023 
- [ ] Neuer Branch vom ember-upgrade-branch ziehen
- [ ] Bootstrap heben (ember-bootstrap ebenfalls wenn nötig)
- [ ] Bootstrap Klassen anpassen, style wiederherstellen
