### ISSUE TITLE
Vulnerability problem solving

### ISSUE THREAD

**Issue by Robin481** [puzzle/cryptopus#699]
Info in the bbt chat

**Comment by MarcEgliP** [comment]
Vorgehen:

- [ ] Dependency mit yarn updaten
- [ ] Testem updaten
- [ ] Alle Verwendungsorte ausfindig machen und kontrollieren das nirgends sonst verwendet wird
- [ ] Funktion nochmals überprüfen: Geht alles noch so wie vorher?
- [ ] Cleanup + Pullrequest stellen
