### ISSUE TITLE
Upgrade ember to 4.0

### ISSUE THREAD

**Issue by kcinay055679** [puzzle/cryptopus#710]

**Comment by kcinay055679** [comment]
I upgraded node to version 18.14 and every dependency that failed after the upgrade.
The frontend by itself starts atm, but not all tests are running fine.
Currently i tried to fix our implementation for displaying our changelog.md in html.
The current Idea is to download the current changelog from the github master and use marked to convert the markdown code to hbs. The conversion works fine but right now i'm unable to download the changelog due to Cors errror, i guess.

**Comment by lkleisa** [comment]
Please check, that pipeline is running with new node: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by mtnstar** [comment]
```Experimental support for decorators is a feature that is subject to change in  
      a future release. Set the 'experimentalDecorators' option in your 'tsconfig'   
         or 'jsconfig' to remove this warning. (tsserver 1219) ```

**Comment by kcinay055679** [comment]
https://github.com/puzzle/skills/issues/480#issuecomment-1463832595

**Comment by MarcEgliP** [comment]
Fehler beim Precompilen des Frontends:

None of the “sha512” hashes in the integrity attribute match the content of the subresource

**Comment by kcinay055679** [comment]
https://github.com/embroider-build/ember-auto-import/issues/420

**Comment by MarcEgliP** [comment]
Strategie für den heutigen Tag:

- [ ] Ursache für nicht funktionales Routing finden
  - [ ] Evtl. Seite nicht geladen?
  - [ ] Sind alle nötigen Dependencies up-to-date?
  - [ ] Erkenntnisse in diesem Ticket dokumentieren
- [ ] Fehler beheben
- [ ] Branch mit funktionalem Routing Pushen

**Comment by MarcEgliP** [comment]
## Strategie 13.07.2023
### ToolTip
- [ ] Mit Päscu besprechen
- [ ] Problem fixen 

### Create Problem
=> Wenn zuerst Team Create erstellt, danach Encryptable erstellt => Fehler
- [ ] Ursache dafür finden
- [ ] Ursache beheben

### Changelog
- [ ] Ursache für Fail finden
- [ ] Fehler beheben
- [ ] Branch mit funktionierendem Changelog pushen

**Comment by MarcEgliP** [comment]
## Strategie 14.07.2023
### Tests
- [ ] Failing Tests durchgehen
- [ ] Fehler untersuchen
- [ ] Fehler beheben
- [ ] Vorgehen wiederholen bis alle Tests laufen
- [ ] Branch mit laufenden Frontend Specs pushen

**Comment by MarcEgliP** [comment]
## Entdeckte Bugs auf der Produktion
- FileUpload => Broke => Validation funktioniert nicht
                       => Nach Upload desselben Files im Fileupload => Fail des Uploads

**Comment by MarcEgliP** [comment]
## Strategie 17.07.2023
### Frontend Tests
- [ ] Grund für den Fehler bei dem einten Test SBG
- [ ] Fehler beheben
- [ ] Branch mit funktionierenden Frontend Specs pushen

### System Specs
- [ ] Failing Test mit @mtnstar besprechen
- [ ] System Specs fixen
- [ ] Funktionierender Branch pushen

**Comment by MarcEgliP** [comment]
### Cleanup
- [ ] Changes mit @mtnstar besprechen

### Benchmark
- [ ] Seeder ausfindig machen / mit mehr Daten befüllen
- [ ] Performance nach Einsatz grösserer Datenmengen überprüfen
- [ ] Anpsassungen vornehmen wenn Performance unter hohen Datenmengen leidet

### Review
- [ ] Erstes Review anfordern
- [ ] Requested changes umsetzen
