### ISSUE TITLE
CCLI: Implement improvements

### ISSUE THREAD

**Issue by lkleisa** [puzzle/cryptopus#726]
In [Ticket 720](https://github.com/puzzle/cryptopus/issues/720) we made a new concept for the [Cryptopus CLI](https://github.com/puzzle/ccli). Implement now one of the suggestion

# TODO
- [x] Decide for one suggestion
- [x] Add this suggestion to this ticket description
- [x] Implement suggestion
- [x] Test it

**Comment by njaeggi** [comment]
Modal wurde implementiert, CCLI Custom Attrs PR ist fertig, was noch fehlt sind Tests bei https://github.com/puzzle/cryptopus/pull/737

**Comment by kcinay055679** [comment]
Due to very limited usage of the CCLI, we have decided not to maintain it any further.
