### ISSUE TITLE
API Authorization Headers for CCLI methods

### ISSUE THREAD

**Issue by njaeggi** [puzzle/cryptopus#741]
Currently, everything the CCLI can do is get encryptables, in CCLI we don't have an active User session so we get the private key from the user like this

`current_user.decrypt_private_key(password_header)`

This is in the method decrypted_team_password

Think about what we want to add to CCLI (update, create, delete) and only allow certain methods via api without session (with authorization headers)

All the other requests, that can't be used with CCLI, will not work with the plain API, since there is no way of getting it via headers and there is no existing session

**Comment by kcinay055679** [comment]
Due to very limited usage of the CCLI, we have decided not to maintain it any further.
