### ISSUE TITLE
fix country codes

### ISSUE THREAD

**Issue by psunix** [puzzle/cryptopus#75]
![latest-screenshot](https://user-images.githubusercontent.com/655627/31723897-6b5f2962-b420-11e7-8a71-6611d8edd781.png)

shouldn't the country code for switzerland be CH instead of CHE ?
use official country codes !

**Comment by ombre8** [comment]
Are we talking trigram or digram or not Nato country codes at all? Digram would be SZ

https://en.wikipedia.org/wiki/List_of_NATO_country_codes

**Comment by kallies** [comment]
I guess it's [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166-1) related not Nato Country codes

Alpha-2: CH, DE, ...
Alpha-3: CHE, DEU, ..

**Comment by psunix** [comment]
i'm more familiar with two-letter country codes and would suggest changing to those. 
any objections ?
