### ISSUE TITLE
Search does not work on deepest level anymore

### ISSUE THREAD

**Issue by rece2** [puzzle/cryptopus#752]
In earlier versions the search worked not only on the structure but although on the pwd elements in a folder. So if there is a folder with a lot of entries only the entries matching the search have been in the result list. The actual search seems to search only on folder level.

**Comment by bihorco36** [comment]
Same Issue, if a Password Search appears in a Folder all the Passwords in the given Folder are shown instead of only the one matching.

**Comment by nerrehmit** [comment]
any progress on this? It's the same issue that I reported in the internal chat: https://chat.puzzle.ch/channel/cryptopus/thread/8ZMSGNQPkSddzcHm2

In big folders this behaviour makes the search almost useless. Do you need any help reproducing it or any infos about browsers?

**Comment by mtnstar** [comment]
@nerrehmit we will check this as soon as possible. Lernende are back by the end of January 2024, and they will look into it as a first priority. maybe we find some time earlier, but we're pretty busy with other projects at the moment

**Comment by mtnstar** [comment]
fixed in release 5.3
