### ISSUE TITLE
Fix Flash Login Message

### ISSUE THREAD

**Issue by MarcEgliP** [puzzle/cryptopus#764]
As soon as we login we get constantly some 400 errors when making a GET call to get the env_settings. This is because rails can't find the translation of the login-message inside the env_settings_controller.

Acceptance Criteria:
- [ ] No more 400 when calling to env_settings
- [ ] The translation is either created of modified so that rails can find it
- [ ] All tests are running

**Comment by MarcEgliP** [comment]
It looks like i18n can't find the translation when switching to swiss german. After we switched to swiss german we get constantly 400 Errors and we have to double-click almost every folder / account. If you set a binding.pry inside the env-settings controller you can see that the translation can't find the "time.formats.long" key. For some reasen, we don't have this key in any other translation file, which means something has to be wrong with this key.

**Comment by mtnstar** [comment]
can not be reproduced
