### ISSUE TITLE
When deleting a User with Teams that needed to be deleted first, one needs to reload the page

### ISSUE THREAD

**Issue by ombre8** [puzzle/cryptopus#765]
I needed to delete a User in our cryptopus today, said user had 2 Teams which needed to be deleted first, since this User was the last User of this Team. I got a nicely styled Alert, which allowed me to delete those 2 Teams directly. So far so good, but now to the confusing part. I never noticed any information about if those team got deleted or not, and I was still not able to delete the user until I reloaded the whole `admin/users` page and tried to delete the User again. Now, to my surprise, there are no teams attached to that user anymore...

I expected the page to automagicly reload the Team List and remove the Teams when they got deleted and let me delete the user as well as soon there is no Team left...

**Comment by Robin481** [comment]
Heya, thanks for your report.
I'll plan the issue for the sprint starting next monday :v:
